name: Release as OCI images

on:
    push:
        branches:
        - main
jobs:

  publish-image:
    name: Publish OCI image to GitHub Container Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - image: ghcr.io/bluedynamics/mximages-plone/mx-plone-backend
          dockerfile: ./backend/Dockerfile
        - image: ghcr.io/bluedynamics/mximages-plone/mx-plone-frontend
          dockerfile: ./frontend/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}.{{patch}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: "."
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            PACKAGE_VERSION=${{ steps.meta.outputs.version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

